app:
    base-url: ${APP_BASE_URL}
spring:
    application:
        name: gui4me
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    docker:
        compose:
            enabled: false
    web:
        resources:
            static-locations[0]: "file:src/main/resources/static/"
            static-locations[1]: "classpath:/static/"
    flyway:
        enabled: true
        schemas: public
        default-schema: public

    mail:
        host: smtp-relay.brevo.com
        port: 587
        username: ${BREVO_USERNAME}
        password: ${BREVO_PASSWORD}
        from: gui4me.ltda@gmail.com
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
gg:
    jte:
        developmentMode: true
        usePrecompiledTemplates: false

logging:
    level:
        org:
            springframework:
                security: DEBUG
tomtom:
    api-key: ${TOMTOM_API_KEY}
