spring:
    application:
        name: gui4me
    jpa:
        hibernate:
            ddl-auto: validate
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    docker:
        compose:
            enabled: false
    flyway:
        enabled: true
        schemas: public
        default-schema: public


gg:
    jte:
        developmentMode: false
        usePrecompiledTemplates: true

logging:
    level:
        org:
            springframework:
                security: ERROR
tomtom:
    api-key: ${TOMTOM_API_KEY}
