spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gui4me
    username: admin
    password: 1234
  application:
    name: gui4me
  jpa:
    hibernate:
      ddl-auto: update

gg:
  jte:
    developmentMode: true

logging:
  level:
    org:
      springframework:
        security: ERROR #change to DEBUG or INFO for more information about spring security