spring:
  application:
    name: gui4me
  jpa:
    hibernate:
      ddl-auto: update

gg:
  jte:
    developmentMode: true

logging:
  level:
    org:
      springframework:
        security: ERROR #change to DEBUG or INFO for more information about spring security