spring:
  application:
    name: gui4me
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  docker:
    compose:
      enabled: false
  web:
    resources:
      static-locations[0]: "file:src/main/resources/static/"
      static-locations[1]: "classpath:/static/"


gg:
  jte:
    developmentMode: true
    usePrecompiledTemplates: false

logging:
  level:
    org:
      springframework:
        security: DEBUG