spring:
  application:
    name: gui4me
  jpa:
    hibernate:
      ddl-auto: update

gg:
  jte:
    developmentMode: false
    usePrecompiledTemplates: true

logging:
  level:
    org:
      springframework:
        security: DEBUG