app:
    base-url: ${APP_BASE_URL}
spring:
    application:
        name: gui4me
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    docker:
        compose:
            enabled: false
    web:
        resources:
            static-locations[0]: "file:src/main/resources/static/"
            static-locations[1]: "classpath:/static/"
    flyway:
        enabled: true
        schemas: public
        default-schema: public
brevo:
    key: ${BREVO_API_KEY}
    url: https://api.brevo.com/v3/smtp/email
    enabled: false
gg:
    jte:
        developmentMode: true
        usePrecompiledTemplates: false

logging:
    level:
        org:
            springframework:
                security: DEBUG
tomtom:
    api-key: ${TOMTOM_API_KEY}
