app:
    base-url: ${APP_BASE_URL}
spring:
    application:
        name: gui4me
    jpa:
        hibernate:
            ddl-auto: validate
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    docker:
        compose:
            enabled: false
    flyway:
        enabled: true
        schemas: public
        default-schema: public
brevo:
    key: ${BREVO_API_KEY}
    url: https://api.brevo.com/v3/smtp/email
    enabled: true
gg:
    jte:
        developmentMode: false
        usePrecompiledTemplates: true

logging:
    level:
        org:
            springframework:
                security: ERROR
tomtom:
    api-key: ${TOMTOM_API_KEY}
